name: Build and Publish Image to Docker Hub

on:
  workflow_dispatch:
  
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: danielsyahputra13
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: danielsyahputra13/rest-api-cpp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
